######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 18 00:11:49 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
