/*  We'll start by writing the function which reacts to the signal
    which is passed in the parameter sig.
    This is the function we will arrange to be called when a signal occurs.
    We print a message, then reset the signal handling for SIGINT
    (by default generated by pressing CTRL-C) back to the default behavior.
    Let's call this function ouch.  */

#include <signal.h>
#include <stdio.h>
#include <unistd.h>

void ouch(int sig)//参数是当前传递的是什么信号
{
    printf("OUCH! - I got signal %d\n", sig);
    (void) signal(SIGINT, SIG_DFL);
	printf("%p\n", signal(SIGINT, SIG_DFL));
}

/*  The main function has to intercept the SIGINT signal generated when we type Ctrl-C .
    For the rest of the time, it just sits in an infinite loop,
    printing a message once a second.  */

int main()
{
	printf("%p\n", signal(SIGINT, SIG_DFL));//?可以有灵活应用
    (void) signal(SIGINT, ouch);//压栈自右向做开始，如果压入参数则不知道是谁的

    while(1) {
        printf("Hello World!\n");
        sleep(1);
    }
}
