######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 17 23:45:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += button.cpp
